name: "01 - DEVELOP DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write
  

jobs:
  lambda-deployment:
    uses: ./.github/workflows/lambda-deployment.yaml
    with:
      environment: dev
      create_release: true